spring:
  profiles:
    include: oauth
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    livereload:         
      enabled: true     # Spring devtools = 스프링부트에서 코드를 작성시 자동 리로딩 될수있게 해주는 라이브러리, 그 라이브러리를 활성화 시켜주는 설정
  servlet:
    multipart:                  #파일 업로드시 업로드 파일의 크기설정
      max-file-size: 100MB       #전송되어 오는 파일하나하나의 최대크기,
      max-request-size: 100MB    #전송되는 request 전체의 크기, 
  main:
    allow-circular-references: true 
  thymeleaf:                    #타임리프 설정, 
    enabled: true               # 타임리프를 활성화 시키는 설정,
    prefix: classpath:templates/  # 타임리프의 기본경로 설정
    suffix: .html               # 타임리프로 실행되는 파일의 파일 확장자
    cache: false                # false로 해놓았을 때 타임리프를 수정하고 서버를 재시작할 필요 없이 새로 고침만으로 반영이 된다.개발시 false이후 true,
    encoding: UTF-8             # 타임리프 인코딩 설정
    mode: HTML                  # 타임리프의 HTML 모드설정 HTML5,,
    check-template: true        # 렌더링 전에 template 존재 여부 확인 
    check-template-location: true # template 위치 존재 여부 확인
  datasource:       # HikariCP를 사용하기위한 설정, (DB연결을 위한 커넥션풀) 커넥션풀 = DB와 연결된 커넥션을 미리 만들어놓고 관리하는것, 필요할때마다 커넥션을 이용하고 반환하는 형식,
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root # mysql ID
      password: 1111 # 각자 MYSQL 비밀번호 입력
      connection-test-query: SELECT NOW() FROM dual
  mail:
   host: smtp.gmail.com
   port : 587
   username : kdogather@gmail.com
   password : krvcxhvihruhnofw

mybatis:
  configuration:  
    map-underscore-to-camel-case: true #MyBatis의 표기법인 스네이크케이스 ( 언더바"_" 를 사용해 단어의 이미를 구분)를 ex)camel_case
                                       #자바의 표기법 카멜케이스 방식으로 변환, 첫글자는 소문자로시작 > 중간글자를 대문자 ex)camelCase
server:
  port: 8086

file:
  Upimg: C:/projectimg/    #파일의 저장,출력을 이클립스의 외부경로 ex) C드라이브에서 가져올때 MvcConfig에서 사용할 경로의 값을 미리 선언,
  Upfolder: file:///projectimg/
logging:
  level:
    com:
      zaxxer:
        hikari: TRACE 
        HikariConfig: DEBUG
chart:
  OneWeek: -7 DAY